import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

const inter = Jost({ subsets: ["latin"], weight:[
  '300',
  '400',
  '500',
  '600',
  '700'
]});

export const metadata: Metadata = {
  title: "Elegance Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
